const resist = [{ "targeted" : "abdominals",  "name" :"Full Reverse Crunch"  }, 
{ "targeted" : "abdominals",  "name" :"Incline Hip Thrust"  }, 
{ "targeted" : "abdominals",  "name" :"Incline Reverse Crunch"  }, 
{ "targeted" : "abdominals",  "name" :"Lying Hip Thrust"  }, 
{ "targeted" : "abdominals",  "name" :"Reverse Crunch"  }, 
{ "targeted" : "abdominals",  "name" :"Reverse Medicine Ball Crunch"  }, 
{ "targeted" : "abdominals",  "name" :"Alternating Heel Touch"  }, 
{ "targeted" : "abdominals",  "name" :"Bent-Knee Medicine Ball Hip Rot"  }, 
{ "targeted" : "abdominals",  "name" :"Cable Chop"  }, 
{ "targeted" : "abdominals",  "name" :"Cross Crunch"  }, 
{ "targeted" : "abdominals",  "name" :"Cross Crunch with Medicine Ball"  }, 
{ "targeted" : "abdominals",  "name" :"Decline Cross Sit-Up"  }, 
{ "targeted" : "abdominals",  "name" :"Decline Sit-Up with Twist"  }, 
{ "targeted" : "abdominals",  "name" :"Reverse Cable Chop"  }, 
{ "targeted" : "abdominals",  "name" :"Seated Medicine Ball Twist"  }, 
{ "targeted" : "abdominals",  "name" :"Trunk Rotator"  }, 
{ "targeted" : "abdominals",  "name" :"Front Plank -from knees"  }, 
{ "targeted" : "abdominals",  "name" :"Front Plank -from toes"  }, 
{ "targeted" : "abdominals",  "name" :"Front Plank -tripod"  }, 
{ "targeted" : "abdominals",  "name" :"Side-Plank -from knees"  }, 
{ "targeted" : "abdominals",  "name" :"Side-Plank -hip lift"  }, 
{ "targeted" : "abdominals",  "name" :"Side-Plank -from toes"  }, 
{ "targeted" : "abdominals",  "name" :"Ab Cycle"  }, 
{ "targeted" : "abdominals",  "name" :"Kneeling Ab Rollout"  }, 
{ "targeted" : "abdominals",  "name" :"Medicine Ball V-Up"  }, 
{ "targeted" : "abdominals",  "name" :"V-Up"  }, 
{ "targeted" : "abdominals",  "name" :"Weighted V-Up"  }, 
{ "targeted" : "abdominals",  "name" :"Bent Knee Sit-Up"  }, 
{ "targeted" : "abdominals",  "name" :"Bent-Knee Crunch"  }, 
{ "targeted" : "abdominals",  "name" :"Crunch"  }, 
{ "targeted" : "abdominals",  "name" :"Crunch"  }, 
{ "targeted" : "abdominals",  "name" :"Decline Crunch"  }, 
{ "targeted" : "abdominals",  "name" :"Decline Sit-Up"  }, 
{ "targeted" : "abdominals",  "name" :"Heel Touch"  }, 
{ "targeted" : "abdominals",  "name" :"Sit-Up"  }, 
{ "targeted" : "abdominals",  "name" :"Weighted Crunch"  }, 
{ "targeted" : "lats",  "name" :"Assisted Pull-Up"  }, 
{ "targeted" : "lats",  "name" :"Close-Grip Lat Pulldown"  }, 
{ "targeted" : "lats",  "name" :"Inverted Pull-Up"  }, 
{ "targeted" : "lats",  "name" :"Lat Pulldown"  }, 
{ "targeted" : "lats",  "name" :"Pull-Up"  }, 
{ "targeted" : "lats",  "name" :"Reverse-Grip Lat Pullown"  }, 
{ "targeted" : "lats",  "name" :"Reverse-Grip Pull-Up"  }, 
{ "targeted" : "lats",  "name" :"V-Bar Pull-Up"  }, 
{ "targeted" : "lats",  "name" :"Wide-Grip Lat Pulldown"  }, 
{ "targeted" : "lats",  "name" :"Bent-Over Alternating Dumbbell Row"  }, 
{ "targeted" : "lats",  "name" :"Bent-Over Barbell Row"  }, 
{ "targeted" : "lats",  "name" :"Bent-Over Dumbbell Row"  }, 
{ "targeted" : "lats",  "name" :"Bent-Over Hammer Dumbbell Row"  }, 
{ "targeted" : "lats",  "name" :"Bent-Over Long Barbell Row"  }, 
{ "targeted" : "lats",  "name" :"Bent-Over Reverse-Grip Barbell Row"  }, 
{ "targeted" : "lats",  "name" :"Bent-Over Single-Arm Long Barbell Row"  }, 
{ "targeted" : "lats",  "name" :"Machine Row"  }, 
{ "targeted" : "lats",  "name" :"One Arm Dumbbell Row"  }, 
{ "targeted" : "lats",  "name" :"Reverse Incline Dumbbell Row"  }, 
{ "targeted" : "lats",  "name" :"Rope Cable Row"  }, 
{ "targeted" : "lats",  "name" :"Seated Cable Row"  }, 
{ "targeted" : "lats",  "name" :"Seated Row"  }, 
{ "targeted" : "lats",  "name" :"Single-Arm Cable Row"  }, 
{ "targeted" : "lats",  "name" :"Single-Arm Dumbbell Row"  }, 
{ "targeted" : "lats",  "name" :"Single-Arm Lat Pulldown"  }, 
{ "targeted" : "lats",  "name" :"Standing Cable Row"  }, 
{ "targeted" : "lats",  "name" :"Standing Single-Arm Cable Row"  }, 
{ "targeted" : "biceps",  "name" :"Alternating Hammer Curl"  }, 
{ "targeted" : "biceps",  "name" :"Barbell Curl"  }, 
{ "targeted" : "biceps",  "name" :"Bicep Curl"  }, 
{ "targeted" : "biceps",  "name" :"Bottom/Top/Full Curls"  }, 
{ "targeted" : "biceps",  "name" :"Cable Curl"  }, 
{ "targeted" : "biceps",  "name" :"Concentration Dumbbell Curl"  }, 
{ "targeted" : "biceps",  "name" :"Cross Body Hammer Curl"  }, 
{ "targeted" : "biceps",  "name" :"Dumbbell Curl"  }, 
{ "targeted" : "biceps",  "name" :"EZ-Bar Curl"  }, 
{ "targeted" : "biceps",  "name" :"Hammer Curl"  }, 
{ "targeted" : "biceps",  "name" :"Incline Alternating Dumbbell Curl"  }, 
{ "targeted" : "biceps",  "name" :"Incline Alternating Hammer Curl"  }, 
{ "targeted" : "biceps",  "name" :"Incline Dumbbell Curl"  }, 
{ "targeted" : "biceps",  "name" :"Incline Hammer Curl"  }, 
{ "targeted" : "biceps",  "name" :"Kneeling Cable Curl"  }, 
{ "targeted" : "biceps",  "name" :"Lying Cable Curl"  }, 
{ "targeted" : "biceps",  "name" :"Lying Double Biceps Cable Curl"  }, 
{ "targeted" : "biceps",  "name" :"Lying High Cable Curl"  }, 
{ "targeted" : "biceps",  "name" :"Machine Curl"  }, 
{ "targeted" : "biceps",  "name" :"Overhead Double Biceps Cable Curl"  }, 
{ "targeted" : "biceps",  "name" :"Overhead Rope Cable Curl"  }, 
{ "targeted" : "biceps",  "name" :"Preacher Barbell Curl"  }, 
{ "targeted" : "biceps",  "name" :"Preacher Cable Curl"  }, 
{ "targeted" : "biceps",  "name" :"Preacher Dumbbell Curl"  }, 
{ "targeted" : "biceps",  "name" :"Preacher EZ-Bar Curl"  }, 
{ "targeted" : "biceps",  "name" :"Preacher Hammer Dumbbell Curl"  }, 
{ "targeted" : "biceps",  "name" :"Preacher Single-Arm Dumbbell Curl"  }, 
{ "targeted" : "biceps",  "name" :"Reverse Curl"  }, 
{ "targeted" : "biceps",  "name" :"Rope Cable Curl"  }, 
{ "targeted" : "biceps",  "name" :"Seated Alternating Curl"  }, 
{ "targeted" : "biceps",  "name" :"Seated Alternating Hammer Curl"  }, 
{ "targeted" : "biceps",  "name" :"Seated Dumbbell Curl"  }, 
{ "targeted" : "biceps",  "name" :"Seated Hammer Curl"  }, 
{ "targeted" : "biceps",  "name" :"Single-Arm Barbell Curl"  }, 
{ "targeted" : "biceps",  "name" :"Single-Arm Cable Curl"  }, 
{ "targeted" : "biceps",  "name" :"Single-Arm Dumbbell Curl w/ Incline Bench"  }, 
{ "targeted" : "biceps",  "name" :"Spider Curl"  }, 
{ "targeted" : "calves",  "name" :"Barbell Calf Raise"  }, 
{ "targeted" : "calves",  "name" :"Calf Press"  }, 
{ "targeted" : "calves",  "name" :"Calf Raise - Seated"  }, 
{ "targeted" : "calves",  "name" :"Calf Raise - Standing"  }, 
{ "targeted" : "calves",  "name" :"Dumbbell Calf Raise"  }, 
{ "targeted" : "calves",  "name" :"Single-Leg Calf Press"  }, 
{ "targeted" : "calves",  "name" :"Single-Leg Dumbbell Calf Raise"  }, 
{ "targeted" : "calves",  "name" :"Smith Machine Calf Raise"  }, 
{ "targeted" : "calves",  "name" :"Seated Calf Raise"  }, 
{ "targeted" : "calves",  "name" :"Seated Single-Leg Calf Raise"  }, 
{ "targeted" : "chest",  "name" :"Alternating Dumbbell Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Barbell Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Chest Press"  }, 
{ "targeted" : "chest",  "name" :"Decline Dumbbell Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Decline Smith Machine Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Dumbbell Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Dumbbell Push-Up"  }, 
{ "targeted" : "chest",  "name" :"Elevated Push-Up"  }, 
{ "targeted" : "chest",  "name" :"Flat Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Incline Alternating Dumbbell Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Incline Barbell Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Incline Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Incline Dumbbell Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Incline Hammer Dumbbell Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Incline Single-Arm Dumbbell Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Incline Smith Machine Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Incline Twisting Dumbbell Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Kneeling Push-Up"  }, 
{ "targeted" : "chest",  "name" :"Machine Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Machine Vertical Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Medicine Ball Crossover Push-Up"  }, 
{ "targeted" : "chest",  "name" :"Push-Up"  }, 
{ "targeted" : "chest",  "name" :"Single-Arm Dumbbell Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Smith Machine Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Twisting Dumbbell Bench Press"  }, 
{ "targeted" : "chest",  "name" :"Wide-Grip Push-Up"  }, 
{ "targeted" : "chest",  "name" :"Cable Crossover"  }, 
{ "targeted" : "chest",  "name" :"Cable Fly"  }, 
{ "targeted" : "chest",  "name" :"Decline Dumbbell Fly"  }, 
{ "targeted" : "chest",  "name" :"Dumbbell Fly"  }, 
{ "targeted" : "chest",  "name" :"High Cable Crossover"  }, 
{ "targeted" : "chest",  "name" :"Incline Cable Fly"  }, 
{ "targeted" : "chest",  "name" :"Incline Dumbbell Fly"  }, 
{ "targeted" : "chest",  "name" :"Incline Twisting Dumbbell Fly"  }, 
{ "targeted" : "chest",  "name" :"Low Cable Crossover"  }, 
{ "targeted" : "chest",  "name" :"Pec Deck"  }, 
{ "targeted" : "chest",  "name" :"Pec Deck Fly"  }, 
{ "targeted" : "legs",  "name" :"Bent-Knee Single-Leg Hip Lift"  }, 
{ "targeted" : "legs",  "name" :"Elevated Hip Lift"  }, 
{ "targeted" : "legs",  "name" :"Elevated Single-Leg Hip Lift"  }, 
{ "targeted" : "legs",  "name" :"Hip Lift"  }, 
{ "targeted" : "legs",  "name" :"Single-Leg Hip Lift"  }, 
{ "targeted" : "legs",  "name" :"Deadlift"  }, 
{ "targeted" : "legs",  "name" :"Leg Curl"  }, 
{ "targeted" : "legs",  "name" :"Lying Alternating Leg Curl"  }, 
{ "targeted" : "legs",  "name" :"Lying Leg Curl"  }, 
{ "targeted" : "legs",  "name" :"Lying Single-Leg Curl"  }, 
{ "targeted" : "legs",  "name" :"Seated Leg Curl"  }, 
{ "targeted" : "legs",  "name" :"Barbell Diagonal Lunge"  }, 
{ "targeted" : "legs",  "name" :"Barbell Hack Squat"  }, 
{ "targeted" : "legs",  "name" :"Barbell Lunge"  }, 
{ "targeted" : "legs",  "name" :"Barbell Reverse Lunge"  }, 
{ "targeted" : "legs",  "name" :"Barbell Side Lunge"  }, 
{ "targeted" : "legs",  "name" :"Barbell Split Squat"  }, 
{ "targeted" : "legs",  "name" :"Barbell Squat"  }, 
{ "targeted" : "legs",  "name" :"Barbell Step-Up"  }, 
{ "targeted" : "legs",  "name" :"Barbell Walking Lunge"  }, 
{ "targeted" : "legs",  "name" :"Diagonal Lunge"  }, 
{ "targeted" : "legs",  "name" :"Dumbbell Diagonal Lunge"  }, 
{ "targeted" : "legs",  "name" :"Dumbbell Lunge"  }, 
{ "targeted" : "legs",  "name" :"Dumbbell Reverse Lunge"  }, 
{ "targeted" : "legs",  "name" :"Dumbbell Side Lunge"  }, 
{ "targeted" : "legs",  "name" :"Dumbbell Split Squat"  }, 
{ "targeted" : "legs",  "name" :"Dumbbell Squat"  }, 
{ "targeted" : "legs",  "name" :"Dumbbell Step-Up"  }, 
{ "targeted" : "legs",  "name" :"Dumbbell Walking Lunge"  }, 
{ "targeted" : "legs",  "name" :"Forward Lunge"  }, 
{ "targeted" : "legs",  "name" :"Lateral Barbell Squat"  }, 
{ "targeted" : "legs",  "name" :"Lateral Barbell Step-Up"  }, 
{ "targeted" : "legs",  "name" :"Lateral Squat"  }, 
{ "targeted" : "legs",  "name" :"Lateral Step-Up"  }, 
{ "targeted" : "legs",  "name" :"Leg Press"  }, 
{ "targeted" : "legs",  "name" :"Lunge"  }, 
{ "targeted" : "legs",  "name" :"Lying Machine Squat"  }, 
{ "targeted" : "legs",  "name" :"Machine Hack Squat"  }, 
{ "targeted" : "legs",  "name" :"Reverse Lunge"  }, 
{ "targeted" : "legs",  "name" :"Single-Arm Barbell Side Squat"  }, 
{ "targeted" : "legs",  "name" :"Single-Arm Dumbbell Side Squat"  }, 
{ "targeted" : "legs",  "name" :"Single-Leg Barbell Squat"  }, 
{ "targeted" : "legs",  "name" :"Single-Leg Box Squat"  }, 
{ "targeted" : "legs",  "name" :"Single-Leg Dumbbell Box Squat"  }, 
{ "targeted" : "legs",  "name" :"Single-Leg Dumbbell Squat"  }, 
{ "targeted" : "legs",  "name" :"Single-Leg Squat"  }, 
{ "targeted" : "legs",  "name" :"Smith Machine Squat"  }, 
{ "targeted" : "legs",  "name" :"Split Squat"  }, 
{ "targeted" : "legs",  "name" :"Step-Up"  }, 
{ "targeted" : "legs",  "name" :"Walking Lunge"  }, 
{ "targeted" : "legs",  "name" :"Alternating Leg Ext"  }, 
{ "targeted" : "legs",  "name" :"Leg Ext"  }, 
{ "targeted" : "legs",  "name" :"Single-Leg Ext"  }, 
{ "targeted" : "back",  "name" :"Alternating Superman"  }, 
{ "targeted" : "back",  "name" :"Back Raise"  }, 
{ "targeted" : "back",  "name" :"Quadruped Alternating Superman"  }, 
{ "targeted" : "back",  "name" :"Superman"  }, 
{ "targeted" : "back",  "name" :"Superman Hold"  }, 
{ "targeted" : "shoulders",  "name" :"Arnold Dumbbell Press"  }, 
{ "targeted" : "shoulders",  "name" :"Barbell Shoulder Press"  }, 
{ "targeted" : "shoulders",  "name" :"Dumbbell Alternating Shoulder Press"  }, 
{ "targeted" : "shoulders",  "name" :"Dumbbell Front Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Dumbbell Shoulder Press"  }, 
{ "targeted" : "shoulders",  "name" :"Dumbbell Twisting Shoulder Press"  }, 
{ "targeted" : "shoulders",  "name" :"Machine Shoulder Press"  }, 
{ "targeted" : "shoulders",  "name" :"Seated Dumbbell Rear Delt Elbow Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Single-Arm Dumbbell Shoulder Press"  }, 
{ "targeted" : "shoulders",  "name" :"Smith Machine Shoulder Press"  }, 
{ "targeted" : "shoulders",  "name" :"Barbell Front Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Bent-Over Cable Rear Delt Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Bent-Over Dumbbell Rear Delt Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Cable Front Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Cable Lateral Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Dumbbell Lateral Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Front Plate Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Kneeling Single-Arm Cable Rear Delt Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Lying Dumbbell External Rot"  }, 
{ "targeted" : "shoulders",  "name" :"Lying Dumbbell Rear Delt Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Lying Single-Arm Dumbbell Rear Delt Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Pec Deck Real Delt Exts"  }, 
{ "targeted" : "shoulders",  "name" :"Reverse Incline Dumbbell Rear Delt Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Seated Dumbbell Rear Delt Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Single-Arm Cable Lateral Raise"  }, 
{ "targeted" : "shoulders",  "name" :"Cable External Rot"  }, 
{ "targeted" : "triceps",  "name" :"Close-Grip Bench Press"  }, 
{ "targeted" : "triceps",  "name" :"Forward Lean Dips"  }, 
{ "targeted" : "triceps",  "name" :"Assisted Dips"  }, 
{ "targeted" : "triceps",  "name" :"Bench Dips"  }, 
{ "targeted" : "triceps",  "name" :"Diamond Push-Up"  }, 
{ "targeted" : "triceps",  "name" :"Dips"  }, 
{ "targeted" : "triceps",  "name" :"Machine Dips"  }, 
{ "targeted" : "triceps",  "name" :"Decline Dumbbell Triceps Ext"  }, 
{ "targeted" : "triceps",  "name" :"Decline EZ-Bar Tricep Ext"  }, 
{ "targeted" : "triceps",  "name" :"Decline Single Dumbbell Triceps Ext"  }, 
{ "targeted" : "triceps",  "name" :"Decline Single-Arm Dumbbell Triceps Ext"  }, 
{ "targeted" : "triceps",  "name" :"Dumbbell Kickback"  }, 
{ "targeted" : "triceps",  "name" :"Incline EZ-Bar Tricep Ext"  }, 
{ "targeted" : "triceps",  "name" :"Kneeling Cable Triceps Ext"  }, 
{ "targeted" : "triceps",  "name" :"Leaning Overhead Tricep Ext"  }, 
{ "targeted" : "triceps",  "name" :"Low Cable Triceps Ext"  }, 
{ "targeted" : "triceps",  "name" :"Lying Cable Triceps Ext"  }, 
{ "targeted" : "triceps",  "name" :"Lying EZ-Bar Triceps Ext"  }, 
{ "targeted" : "triceps",  "name" :"Lying Overhead EZ-Bar Tricep Ext"  }, 
{ "targeted" : "triceps",  "name" :"Lying Reverse EZ-Bar Triceps Ext"  }, 
{ "targeted" : "triceps",  "name" :"Lying Single Dumbbell Triceps Ext"  }, 
{ "targeted" : "triceps",  "name" :"Lying Single-Arm Dumbbell Triceps Ext"  }, 
{ "targeted" : "triceps",  "name" :"Lying Tricep Exts"  }, 
{ "targeted" : "triceps",  "name" :"Overhead Dumbbell Triceps Ext"  }, 
{ "targeted" : "triceps",  "name" :"Overhead EZ-Bar Triceps Ext"  }, 
{ "targeted" : "triceps",  "name" :"Overhead Rope Cable Tricep Ext"  }, 
{ "targeted" : "triceps",  "name" :"Overhead Single Dumbbell Tricep Ext"  }, 
{ "targeted" : "triceps",  "name" :"Overhead Single-Arm Cable Tricep Ext"  }, 
{ "targeted" : "triceps",  "name" :"Overhead Single-Arm Dumbbell Tricep Ext"  }, 
{ "targeted" : "triceps",  "name" :"Reverse Tricep Pushdown"  }, 
{ "targeted" : "triceps",  "name" :"Rope Triceps Pushdown"  }, 
{ "targeted" : "triceps",  "name" :"Single-Arm Towel Triceps Pushdown"  }, 
{ "targeted" : "triceps",  "name" :"Single-Arm Triceps Pushdown"  }, 
{ "targeted" : "triceps",  "name" :"Towel Triceps Pushdown"  }, 
{ "targeted" : "triceps",  "name" :"Tricep Exts"  }, 
{ "targeted" : "triceps",  "name" :"Tricep Pushdown"  }, 
{ "targeted" : "triceps",  "name" :"Tricep Pushdown"  }, 
{ "targeted" : "triceps",  "name" :"V-Bar Tricep Pushdown"  }]
;


module.exports = 
  resist
;
