const resistance = [
  {
    unq_id: 1,
    category: 'Abdominals',
    muscles: 'Abs-Lower',
    name: 'Full Reverse Crunch',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 2,
    category: 'Abdominals',
    muscles: 'Abs-Lower',
    name: 'Incline Hip Thrust',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 3,
    category: 'Abdominals',
    muscles: 'Abs-Lower',
    name: 'Incline Reverse Crunch',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 4,
    category: 'Abdominals',
    muscles: 'Abs-Lower',
    name: 'Lying Hip Thrust',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 5,
    category: 'Abdominals',
    muscles: 'Abs-Lower',
    name: 'Reverse Crunch',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 6,
    category: 'Abdominals',
    muscles: 'Abs-Lower',
    name: 'Reverse Medicine Ball Crunch',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 7,
    category: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Alternating Heel Touch',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 8,
    category: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Bent-Knee Medicine Ball Hip Rot',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 9,
    category: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Cable Chop',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 10,
    category: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Cross Crunch',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 11,
    category: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Cross Crunch with Medicine Ball',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 12,
    category: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Decline Cross Sit-Up',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 13,
    category: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Decline Sit-Up with Twist',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 14,
    category: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Reverse Cable Chop',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 15,
    category: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Seated Medicine Ball Twist',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 16,
    category: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Trunk Rotator',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 17,
    category: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Front Plank -from knees',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Static',
    mod: 'Free-Weight',
  },
  {
    unq_id: 18,
    category: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Front Plank -from toes',
    difficulty: 'Intermediate',
    area: 'Core',
    split: 'Static',
    mod: 'Free-Weight',
  },
  {
    unq_id: 19,
    category: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Front Plank -tripod',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Static',
    mod: 'Free-Weight',
  },
  {
    unq_id: 20,
    category: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Side-Plank -from knees',
    difficulty: 'Intermediate',
    area: 'Core',
    split: 'Static',
    mod: 'Free-Weight',
  },
  {
    unq_id: 21,
    category: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Side-Plank -hip lift',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Static',
    mod: 'Free-Weight',
  },
  {
    unq_id: 22,
    category: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Side-Plank -from toes',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Static',
    mod: 'Free-Weight',
  },
  {
    unq_id: 23,
    category: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Ab Cycle',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 24,
    category: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Kneeling Ab Rollout',
    difficulty: 'Intermediate',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 25,
    category: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Medicine Ball V-Up',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 26,
    category: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'V-Up',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 27,
    category: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Weighted V-Up',
    difficulty: 'Intermediate',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 28,
    category: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Bent Knee Sit-Up',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 29,
    category: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Bent-Knee Crunch',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 30,
    category: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Crunch',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 31,
    category: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Crunch',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 32,
    category: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Decline Crunch',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 33,
    category: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Decline Sit-Up',
    difficulty: 'Advanced',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 34,
    category: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Heel Touch',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 35,
    category: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Sit-Up',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 36,
    category: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Weighted Crunch',
    difficulty: 'Intermediate',
    area: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 37,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Assisted Pull-Up',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 38,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Close-Grip Lat Pulldown',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Machine',
  },
  {
    unq_id: 39,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Inverted Pull-Up',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 40,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Lat Pulldown',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 41,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Pull-Up',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 42,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Reverse-Grip Lat Pullown',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 43,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Reverse-Grip Pull-Up',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 44,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'V-Bar Pull-Up',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 45,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Wide-Grip Lat Pulldown',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 46,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Alternating Dumbbell Row',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 47,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Barbell Row',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 48,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Dumbbell Row',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 49,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Hammer Dumbbell Row',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 50,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Long Barbell Row',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 51,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Reverse-Grip Barbell Row',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 52,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Single-Arm Long Barbell Row',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 53,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Machine Row',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Machine',
  },
  {
    unq_id: 54,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'One Arm Dumbbell Row',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 55,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Reverse Incline Dumbbell Row',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 56,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Rope Cable Row',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 57,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Seated Cable Row',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 58,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Seated Row',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 59,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Single-Arm Cable Row',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 60,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Single-Arm Dumbbell Row',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 61,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Single-Arm Lat Pulldown',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 62,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Standing Cable Row',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 63,
    category: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Standing Single-Arm Cable Row',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 64,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Alternating Dumbbell Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 65,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Alternating Hammer Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 66,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Barbell Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 67,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Bicep Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 68,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Bottom/Top/Full Curls',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 69,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Cable Curl',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 70,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Concentration Dumbbell Curl',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 71,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Cross Body Hammer Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 72,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Dumbbell Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 73,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'EZ-Bar Curl',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 74,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Hammer Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 75,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Incline Alternating Dumbbell Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 76,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Incline Alternating Hammer Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 77,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Incline Dumbbell Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 78,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Incline Hammer Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 79,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Kneeling Cable Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 80,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Lying Cable Curl',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 81,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Lying Double Biceps Cable Curl',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 82,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Lying High Cable Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 83,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Machine Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Machine',
  },
  {
    unq_id: 84,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Overhead Double Biceps Cable Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 85,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Overhead Rope Cable Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 86,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Preacher Barbell Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 87,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Preacher Cable Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 88,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Preacher Dumbbell Curl',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 89,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Preacher EZ-Bar Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 90,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Preacher Hammer Dumbbell Curl',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 91,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Preacher Single-Arm Dumbbell Curl',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 92,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Reverse Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 93,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Rope Cable Curl',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    unq_id: 94,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Seated Alternating Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 95,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Seated Alternating Hammer Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 96,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Seated Dumbbell Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 97,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Seated Hammer Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 98,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Single-Arm Barbell Curl',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 99,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Single-Arm Cable Curl',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 100,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Single-Arm Dumbbell Curl w/ Incline Bench',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 101,
    category: 'Biceps',
    muscles: 'Biceps',
    name: 'Spider Curl',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 102,
    category: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Barbell Calf Raise',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 103,
    category: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Calf Press',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 104,
    category: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Calf Raise - Seated',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 105,
    category: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Calf Raise - Standing',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 106,
    category: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Dumbbell Calf Raise',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 107,
    category: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Single-Leg Calf Press',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 108,
    category: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Single-Leg Dumbbell Calf Raise',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 109,
    category: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Smith Machine Calf Raise',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 110,
    category: 'Calves',
    muscles: 'Calves-Soleus',
    name: 'Seated Calf Raise',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 111,
    category: 'Calves',
    muscles: 'Calves-Soleus',
    name: 'Seated Single-Leg Calf Raise',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 112,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Alternating Dumbbell Bench Press',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 113,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Barbell Bench Press',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 114,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Chest Press',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 115,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Decline Dumbbell Bench Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 116,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Decline Smith Machine Bench Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 117,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Dumbbell Bench Press',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 118,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Dumbbell Push-Up',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 119,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Elevated Push-Up',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 120,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Flat Bench Press',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 121,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Alternating Dumbbell Bench Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 122,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Barbell Bench Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 123,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Bench Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 124,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Dumbbell Bench Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 125,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Hammer Dumbbell Bench Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 126,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Single-Arm Dumbbell Bench Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 127,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Smith Machine Bench Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 128,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Twisting Dumbbell Bench Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 129,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Kneeling Push-Up',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 130,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Machine Bench Press',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 131,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Machine Vertical Bench Press',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 132,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Medicine Ball Crossover Push-Up',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 133,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Push-Up',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 134,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Single-Arm Dumbbell Bench Press',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 135,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Smith Machine Bench Press',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 136,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Twisting Dumbbell Bench Press',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 137,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Wide-Grip Push-Up',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 138,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Cable Crossover',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 139,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Cable Fly',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 140,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Decline Dumbbell Fly',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 141,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Dumbbell Fly',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 142,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'High Cable Crossover',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 143,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Cable Fly',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 144,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Dumbbell Fly',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 145,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Twisting Dumbbell Fly',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 146,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Low Cable Crossover',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 147,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Pec Deck',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 148,
    category: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Pec Deck Fly',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 149,
    category: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Bent-Knee Single-Leg Hip Lift',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 150,
    category: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Elevated Hip Lift',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 151,
    category: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Elevated Single-Leg Hip Lift',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 152,
    category: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Hip Lift',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 153,
    category: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Single-Leg Hip Lift',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 154,
    category: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Deadlift',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 155,
    category: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Leg Curl',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Pull',
    mod: 'Machine',
  },
  {
    unq_id: 156,
    category: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Lying Alternating Leg Curl',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Pull',
    mod: 'Machine',
  },
  {
    unq_id: 157,
    category: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Lying Leg Curl',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Pull',
    mod: 'Machine',
  },
  {
    unq_id: 158,
    category: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Lying Single-Leg Curl',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Pull',
    mod: 'Machine',
  },
  {
    unq_id: 159,
    category: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Seated Leg Curl',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Pull',
    mod: 'Machine',
  },
  {
    unq_id: 160,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Diagonal Lunge',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 161,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Hack Squat',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 162,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Lunge',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 163,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Reverse Lunge',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 164,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Side Lunge',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 165,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Split Squat',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 166,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Squat',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 167,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Step-Up',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 168,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Walking Lunge',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 169,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Diagonal Lunge',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 170,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Diagonal Lunge',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 171,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Lunge',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 172,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Reverse Lunge',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 173,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Side Lunge',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 174,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Split Squat',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 175,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Squat',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 176,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Step-Up',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 177,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Walking Lunge',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 178,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Forward Lunge',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 179,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Lateral Barbell Squat',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 180,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Lateral Barbell Step-Up',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 181,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Lateral Squat',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 182,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Lateral Step-Up',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 183,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Leg Press',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 184,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Lunge',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 185,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Lying Machine Squat',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 186,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Machine Hack Squat',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 187,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Reverse Lunge',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 188,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Arm Barbell Side Squat',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 189,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Arm Dumbbell Side Squat',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 190,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Leg Barbell Squat',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 191,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Leg Box Squat',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 192,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Leg Dumbbell Box Squat',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 193,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Leg Dumbbell Squat',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 194,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Leg Squat',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 195,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Smith Machine Squat',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 196,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Split Squat',
    difficulty: 'Advanced',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 197,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Step-Up',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 198,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Walking Lunge',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 199,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Alternating Leg Ext',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 200,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Leg Ext',
    difficulty: 'Beginner',
    area: 'Lower',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 201,
    category: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Leg Ext',
    difficulty: 'Intermediate',
    area: 'Lower',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 202,
    category: 'Back',
    muscles: 'LowerBack-ErectorSpinae',
    name: 'Alternating Superman',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 203,
    category: 'Back',
    muscles: 'LowerBack-ErectorSpinae',
    name: 'Back Raise',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 204,
    category: 'Back',
    muscles: 'LowerBack-ErectorSpinae',
    name: 'Quadruped Alternating Superman',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 205,
    category: 'Back',
    muscles: 'LowerBack-ErectorSpinae',
    name: 'Superman',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 206,
    category: 'Back',
    muscles: 'LowerBack-ErectorSpinae',
    name: 'Superman Hold',
    difficulty: 'Beginner',
    area: 'Core',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    unq_id: 207,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Arnold Dumbbell Press',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 208,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Barbell Shoulder Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 209,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Dumbbell Alternating Shoulder Press',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 210,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Dumbbell Front Raise',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 211,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Dumbbell Shoulder Press',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 212,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Dumbbell Twisting Shoulder Press',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 213,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Machine Shoulder Press',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 214,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Seated Dumbbell Rear Delt Elbow Raise',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 215,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Single-Arm Dumbbell Shoulder Press',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 216,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Smith Machine Shoulder Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 217,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Barbell Front Raise',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 218,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Bent-Over Cable Rear Delt Raise',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 219,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Bent-Over Dumbbell Rear Delt Raise',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 220,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Cable Front Raise',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 221,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Cable Lateral Raise',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 222,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Dumbbell Lateral Raise',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 223,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Front Plate Raise',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 224,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Kneeling Single-Arm Cable Rear Delt Raise',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 225,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Lying Dumbbell External Rot',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 226,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Lying Dumbbell Rear Delt Raise',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 227,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Lying Single-Arm Dumbbell Rear Delt Raise',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 228,
    category: 'Shoulders',
    muscles: 'Shoulders-Delt/Traps',
    name: 'Pec Deck Real Delt Exts',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 229,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Reverse Incline Dumbbell Rear Delt Raise',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 230,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Seated Dumbbell Rear Delt Raise',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 231,
    category: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Single-Arm Cable Lateral Raise',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 232,
    category: 'Shoulders',
    muscles: 'Shoulders-RotatorCuff',
    name: 'Cable External Rot',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 233,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Close-Grip Bench Press',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 234,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Forward Lean Dips',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 235,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Assisted Dips',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 236,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Bench Dips',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 237,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Diamond Push-Up',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 238,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Dips',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 239,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Machine Dips',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Machine',
  },
  {
    unq_id: 240,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Decline Dumbbell Triceps Ext',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 241,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Decline EZ-Bar Tricep Ext',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 242,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Decline Single Dumbbell Triceps Ext',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 243,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Decline Single-Arm Dumbbell Triceps Ext',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 244,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Dumbbell Kickback',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 245,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Incline EZ-Bar Tricep Ext',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 246,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Kneeling Cable Triceps Ext',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 247,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Leaning Overhead Tricep Ext',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 248,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Low Cable Triceps Ext',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 249,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying Cable Triceps Ext',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 250,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying EZ-Bar Triceps Ext',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 251,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying Overhead EZ-Bar Tricep Ext',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 252,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying Reverse EZ-Bar Triceps Ext',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 253,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying Single Dumbbell Triceps Ext',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 254,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying Single-Arm Dumbbell Triceps Ext',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 255,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying Tricep Exts',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 256,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Overhead Dumbbell Triceps Ext',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 257,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Overhead EZ-Bar Triceps Ext',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 258,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Overhead Rope Cable Tricep Ext',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 259,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Overhead Single Dumbbell Tricep Ext',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 260,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Overhead Single-Arm Cable Tricep Ext',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 261,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Overhead Single-Arm Dumbbell Tricep Ext',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 262,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Reverse Tricep Pushdown',
    difficulty: 'Advanced',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 263,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Rope Triceps Pushdown',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 264,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Single-Arm Towel Triceps Pushdown',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 265,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Single-Arm Triceps Pushdown',
    difficulty: 'Intermediate',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 266,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Towel Triceps Pushdown',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 267,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Tricep Exts',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    unq_id: 268,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Tricep Pushdown',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 269,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'Tricep Pushdown',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    unq_id: 270,
    category: 'Triceps',
    muscles: 'Triceps',
    name: 'V-Bar Tricep Pushdown',
    difficulty: 'Beginner',
    area: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
];
;

module.exports = resistance;
