const resistance = [
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Lower',
    name: 'Full Reverse Crunch',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Lower',
    name: 'Incline Hip Thrust',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Lower',
    name: 'Incline Reverse Crunch',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Lower',
    name: 'Lying Hip Thrust',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Lower',
    name: 'Reverse Crunch',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Lower',
    name: 'Reverse Medicine Ball Crunch',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Alternating Heel Touch',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Bent-Knee Medicine Ball Hip Rot',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Cable Chop',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Cross Crunch',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Cross Crunch with Medicine Ball',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Decline Cross Sit-Up',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Decline Sit-Up with Twist',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Reverse Cable Chop',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Seated Medicine Ball Twist',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Obliques',
    name: 'Trunk Rotator',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Front Plank -from knees',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Static',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Front Plank -from toes',
    difficulty: 'Intermediate',
    focus: 'Core',
    split: 'Static',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Front Plank -tripod',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Static',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Side-Plank -from knees',
    difficulty: 'Intermediate',
    focus: 'Core',
    split: 'Static',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Side-Plank -hip lift',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Static',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Side-Plank -from toes',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Static',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Ab Cycle',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Kneeling Ab Rollout',
    difficulty: 'Intermediate',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Medicine Ball V-Up',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'V-Up',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Total',
    name: 'Weighted V-Up',
    difficulty: 'Intermediate',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Bent Knee Sit-Up',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Bent-Knee Crunch',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Crunch',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Crunch',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Decline Crunch',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Decline Sit-Up',
    difficulty: 'Advanced',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Heel Touch',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Sit-Up',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Abdominals',
    muscles: 'Abs-Upper',
    name: 'Weighted Crunch',
    difficulty: 'Intermediate',
    focus: 'Core',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Assisted Pull-Up',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Close-Grip Lat Pulldown',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Machine',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Inverted Pull-Up',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Lat Pulldown',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Pull-Up',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Reverse-Grip Lat Pullown',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Reverse-Grip Pull-Up',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'V-Bar Pull-Up',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Wide-Grip Lat Pulldown',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Alternating Dumbbell Row',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Barbell Row',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Dumbbell Row',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Hammer Dumbbell Row',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Long Barbell Row',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Reverse-Grip Barbell Row',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Bent-Over Single-Arm Long Barbell Row',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Machine Row',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Machine',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'One Arm Dumbbell Row',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Reverse Incline Dumbbell Row',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Rope Cable Row',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Seated Cable Row',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Seated Row',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Single-Arm Cable Row',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Single-Arm Dumbbell Row',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Single-Arm Lat Pulldown',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Standing Cable Row',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Lats',
    muscles: 'Latissimus Dorsi',
    name: 'Standing Single-Arm Cable Row',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Alternating Dumbbell Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Alternating Hammer Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Barbell Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Bicep Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Bottom/Top/Full Curls',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Cable Curl',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Concentration Dumbbell Curl',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Cross Body Hammer Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Dumbbell Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'EZ-Bar Curl',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Hammer Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Incline Alternating Dumbbell Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Incline Alternating Hammer Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Incline Dumbbell Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Incline Hammer Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Kneeling Cable Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Lying Cable Curl',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Lying Double Biceps Cable Curl',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Lying High Cable Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Machine Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'M',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Overhead Double Biceps Cable Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Overhead Rope Cable Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Preacher Barbell Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Preacher Cable Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Preacher Dumbbell Curl',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Preacher EZ-Bar Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Preacher Hammer Dumbbell Curl',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Preacher Single-Arm Dumbbell Curl',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Reverse Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Rope Cable Curl',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Cable',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Seated Alternating Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Seated Alternating Hammer Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Seated Dumbbell Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Seated Hammer Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Single-Arm Barbell Curl',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Single-Arm Cable Curl',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Single-Arm Dumbbell Curl w/ Incline Bench',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Biceps',
    muscles: 'Biceps',
    name: 'Spider Curl',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Barbell Calf Raise',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Calf Press',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Calf Raise - Seated',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Calf Raise - Standing',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Dumbbell Calf Raise',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Single-Leg Calf Press',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Single-Leg Dumbbell Calf Raise',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Calves',
    muscles: 'Calves-Gastrocnemius',
    name: 'Smith Machine Calf Raise',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Calves',
    muscles: 'Calves-Soleus',
    name: 'Seated Calf Raise',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Calves',
    muscles: 'Calves-Soleus',
    name: 'Seated Single-Leg Calf Raise',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Alternating Dumbbell Bench Press',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Barbell Bench Press',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Chest Press',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Decline Dumbbell Bench Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Decline Smith Machine Bench Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Dumbbell Bench Press',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Dumbbell Push-Up',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Elevated Push-Up',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Flat Bench Press',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Alternating Dumbbell Bench Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Barbell Bench Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Bench Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Dumbbell Bench Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Hammer Dumbbell Bench Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Single-Arm Dumbbell Bench Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Smith Machine Bench Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Twisting Dumbbell Bench Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Kneeling Push-Up',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Machine Bench Press',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Machine Vertical Bench Press',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Medicine Ball Crossover Push-Up',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Push-Up',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Single-Arm Dumbbell Bench Press',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Smith Machine Bench Press',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Twisting Dumbbell Bench Press',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Wide-Grip Push-Up',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Cable Crossover',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Cable Fly',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Decline Dumbbell Fly',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Dumbbell Fly',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'High Cable Crossover',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Cable Fly',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Dumbbell Fly',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Incline Twisting Dumbbell Fly',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Low Cable Crossover',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Pec Deck',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Chest',
    muscles: 'Chest-Pectoralis',
    name: 'Pec Deck Fly',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Bent-Knee Single-Leg Hip Lift',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Elevated Hip Lift',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Elevated Single-Leg Hip Lift',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Hip Lift',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Single-Leg Hip Lift',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Deadlift',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Leg Curl',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Pull',
    mod: 'M',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Lying Alternating Leg Curl',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Pull',
    mod: 'M',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Lying Leg Curl',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Pull',
    mod: 'M',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Lying Single-Leg Curl',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Pull',
    mod: 'M',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Hamstrings',
    name: 'Seated Leg Curl',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Pull',
    mod: 'M',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Diagonal Lunge',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Hack Squat',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Lunge',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Reverse Lunge',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Side Lunge',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Split Squat',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Squat',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Step-Up',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Barbell Walking Lunge',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Diagonal Lunge',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Diagonal Lunge',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Lunge',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Reverse Lunge',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Side Lunge',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Split Squat',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Squat',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Step-Up',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Dumbbell Walking Lunge',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Forward Lunge',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Lateral Barbell Squat',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Lateral Barbell Step-Up',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Lateral Squat',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Lateral Step-Up',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Leg Press',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Lunge',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Lying Machine Squat',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Machine Hack Squat',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Reverse Lunge',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Arm Barbell Side Squat',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Arm Dumbbell Side Squat',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Leg Barbell Squat',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Leg Box Squat',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Leg Dumbbell Box Squat',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Leg Dumbbell Squat',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Leg Squat',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Smith Machine Squat',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Split Squat',
    difficulty: 'Advanced',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Step-Up',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Walking Lunge',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Alternating Leg Ext',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Leg Ext',
    difficulty: 'Beginner',
    focus: 'Lower',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Legs',
    muscles: 'Legs-Quadriceps',
    name: 'Single-Leg Ext',
    difficulty: 'Intermediate',
    focus: 'Lower',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Back',
    muscles: 'LowerBack-ErectorSpinae',
    name: 'Alternating Superman',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Back',
    muscles: 'LowerBack-ErectorSpinae',
    name: 'Back Raise',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Back',
    muscles: 'LowerBack-ErectorSpinae',
    name: 'Quadruped Alternating Superman',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Back',
    muscles: 'LowerBack-ErectorSpinae',
    name: 'Superman',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Back',
    muscles: 'LowerBack-ErectorSpinae',
    name: 'Superman Hold',
    difficulty: 'Beginner',
    focus: 'Core',
    split: 'Pull',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Arnold Dumbbell Press',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Barbell Shoulder Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Dumbbell Alternating Shoulder Press',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Dumbbell Front Raise',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Dumbbell Shoulder Press',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Dumbbell Twisting Shoulder Press',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Machine Shoulder Press',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Seated Dumbbell Rear Delt Elbow Raise',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Single-Arm Dumbbell Shoulder Press',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Smith Machine Shoulder Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Barbell Front Raise',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Bent-Over Cable Rear Delt Raise',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Bent-Over Dumbbell Rear Delt Raise',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Cable Front Raise',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Cable Lateral Raise',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Dumbbell Lateral Raise',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Front Plate Raise',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Kneeling Single-Arm Cable Rear Delt Raise',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Lying Dumbbell External Rot',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Lying Dumbbell Rear Delt Raise',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Lying Single-Arm Dumbbell Rear Delt Raise',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Pec Deck Real Delt Exts',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Reverse Incline Dumbbell Rear Delt Raise',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Seated Dumbbell Rear Delt Raise',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-Delts/Traps',
    name: 'Single-Arm Cable Lateral Raise',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Shoulders',
    muscles: 'Shoulders-RotatorCuff',
    name: 'Cable External Rot',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Close-Grip Bench Press',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Forward Lean Dips',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Assisted Dips',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Bench Dips',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Diamond Push-Up',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Dips',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Machine Dips',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'M',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Decline Dumbbell Triceps Ext',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Decline EZ-Bar Tricep Ext',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Decline Single Dumbbell Triceps Ext',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Decline Single-Arm Dumbbell Triceps Ext',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Dumbbell Kickback',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Incline EZ-Bar Tricep Ext',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Kneeling Cable Triceps Ext',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Leaning Overhead Tricep Ext',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Low Cable Triceps Ext',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying Cable Triceps Ext',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying EZ-Bar Triceps Ext',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying Overhead EZ-Bar Tricep Ext',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying Reverse EZ-Bar Triceps Ext',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying Single Dumbbell Triceps Ext',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying Single-Arm Dumbbell Triceps Ext',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Lying Tricep Exts',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Overhead Dumbbell Triceps Ext',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Overhead EZ-Bar Triceps Ext',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Overhead Rope Cable Tricep Ext',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Overhead Single Dumbbell Tricep Ext',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Overhead Single-Arm Cable Tricep Ext',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Overhead Single-Arm Dumbbell Tricep Ext',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Reverse Tricep Pushdown',
    difficulty: 'Advanced',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Rope Triceps Pushdown',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Single-Arm Towel Triceps Pushdown',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Single-Arm Triceps Pushdown',
    difficulty: 'Intermediate',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Towel Triceps Pushdown',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Tricep Exts',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Free-Weight',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Tricep Pushdown',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'Tricep Pushdown',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
  {
    targeted: 'Triceps',
    muscles: 'Triceps',
    name: 'V-Bar Tricep Pushdown',
    difficulty: 'Beginner',
    focus: 'Upper',
    split: 'Push',
    mod: 'Cable',
  },
];

module.exports = resistance;
